name: FTP Deploy
on:
  push:
    branches:
      - 'main'
      - 'sub'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: Aoi1591/SHYAK/checkout@v4
      - name: FTP Deploy
        uses: Aoi1591/SHYAK/FTP-Deploy-Action@4.3.4
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
